Add Better Comments

diff --git a/bin/tb b/bin/tb
--- a/bin/tb
+++ b/bin/tb
@@ -1,11 +1,11 @@
 #!/bin/bash
-if test -t 0; then
-  touch /tmp/tb.txt
+if test -t 0; then #If There is nothing piped into the command
+  touch /tmp/tb.txt #Create TMP file for the editor
   exec 3>&1;
-  TEXT=$(dialog --editbox /tmp/tb.txt 40 40 2>&1 1>&3);
-  exitcode=$?;
+  TEXT=$(dialog --editbox /tmp/tb.txt 40 40 2>&1 1>&3); #Run the Dialog Editor on the tmp file
+  exitcode=$?; #Save The Exit Code
   exec 3>&-;
-  dialog --title 'Message' --msgbox "$(echo $TEXT | nc termbin.com 9999)" 5 50
-else
-  echo "$(cat -)" | nc termbin.com 9999 #Take Input and upload to termbin using NetCat
-fi
+  dialog --title 'Message' --msgbox "$(echo $TEXT | nc termbin.com 9999)" 5 50 #Display Message box with termbin link
+else #If There is something piped into the command
+  echo "$(cat -)" | nc termbin.com 9999 #Take Pipe into and send to termbin, echoing out the termbin link when done.
+fi #End If Statement
